config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords' }
  resources :users, only: [:show] do
    member do
      get :followers, :following
    end
  end
  resources :follow_relationships, only: [:create, :destroy]

  patch 'update_user_professions' => 'users#update_user_professions'
  put 'update_user_professions' => 'users#update_user_professions'
  patch 'update_user_profile_pic' => 'users#update_user_profile_pic'
  put 'update_user_profile_pic' => 'users#update_user_profile_pic'

  resources :professions

  get 'typeahead_professions' => 'professions#typeahead_professions'

  get 'welcome/add_profession' => 'welcome#add_profession'
  get 'welcome/add_profile_pic' => 'welcome#add_profile_pic'
  get 'welcome/add_interests' => 'welcome#add_interests'
  get 'welcome/follow_people' => 'welcome#follow_people'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :check_user

  # GET /welcome/add_profession
  def add_profession
    @user = current_user
    if !@user.professions.any?
      @user.professions.build
    end
  end

  # GET /welcome/add_profile_pic
  def add_profile_pic
    @user = current_user
  end

  # GET /welcome/add_interests
  def add_interests
    
  end

  # GET /welcome/follow_people
  def follow_people
    
  end

  private

    # if user is not signed in redirect to root
    def check_user
      if !user_signed_in?
        redirect_to root_path
      end
    end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/add_interests.html.haml
.container.container-default
  .row
    .col-xs-12
      %h1 Add interests

      = link_to 'Skip', welcome_follow_people_path

app/views/welcome/add_profession.html.haml
.container.container-default
  .row
    .col-xs-12
      %h1 Dada

      = simple_form_for(@user, as: resource_name, url: update_user_professions_path, html: { method: :put }) do |f|
        = render partial: 'shared/error_messages', locals: { target: resource }
        = f.simple_fields_for :professions, include_id: false do |p|
          = p.label :name, 'Tell who you are. For example Student, Manager, Bartender...'
          = p.input :name, placeholder: 'Profession', label: false, input_html: { class: 'typeahead' } 
        = f.button :submit, 'Next', class: 'btn btn-success btn-full-width'

      = link_to 'Skip', welcome_add_profile_pic_path

app/views/welcome/add_profile_pic.html.haml
.container.container-default
  .row
    .col-xs-12
      %h1 Add your profile photo!

      = simple_form_for @user, url: update_user_profile_pic_path do |f|
        .the-profile-pic-upload
          = f.input :profile_pic, as: :file, label: false, input_html: { class: 'cropit-image-input' }
          = f.input :crop_x, as: :hidden, input_html: { id: 'cropX' }
          = f.input :crop_y, as: :hidden, input_html: { id: 'cropY' }
          = f.input :crop_ratio, as: :hidden, input_html: { id: 'cropRatio' }
          .cropit-image-preview-container
            .cropit-image-preview
          
          .image-size-label
            Resize image
          %input.cropit-image-zoom-input{:type => "range"}

          = f.button :submit, 'Continue', class: 'btn btn-success full-width'

      = link_to 'Skip', welcome_add_interests_path

app/views/welcome/follow_people.html.haml
.container.container-default
  .row
    .col-xs-12
      %h1 Bla

      %div
        bla
        .pull-right
          .the-checkbox-container
            %label.the-follow-all
              Follow all
            %a.the-checkbox.the-checkbox-all.the-check-all-people{:href => '#'}
              %span.fa.fa-check-square
            %a.the-checkbox.the-checkbox-all.the-uncheck-all-people.hidden{:href => '#'}
              %span.fa.fa-square-o
            %input.the-checkbox-all-real{:type => 'checkbox', :checked => true}

      .the-following-people
        - User.all.each do |user|
          - unless user == current_user
            .the-header
              = image_tag user.profile_pic.url(:small), class: 'img-rounded'
              .the-name-and-professions
                .the-name
                  = link_to user.full_name, user
                .the-professions
                  Bla
                  |
                  Web bla
                  |
                  blabla
                  |
                  smthing

              .pull-right
                .the-checkbox-container
                  %a.the-checkbox.the-checkbox-single.the-check-person{:href => '#'}
                    %span.fa.fa-check-square
                  %a.the-checkbox.the-checkbox-single.the-uncheck-person.hidden{:href => '#'}
                    %span.fa.fa-square-o
                  
                  %input.the-checkbox-real{:type => 'checkbox', :checked => true}
                     
            %hr.small-margin