config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords' }
  resources :users, only: [:show] do
    member do
      get :followers, :following
    end
  end
  resources :follow_relationships, only: [:create, :destroy]

  patch 'update_user_professions' => 'users#update_user_professions'
  put 'update_user_professions' => 'users#update_user_professions'
  patch 'update_user_profile_pic' => 'users#update_user_profile_pic'
  put 'update_user_profile_pic' => 'users#update_user_profile_pic'

  resources :professions

  get 'typeahead_professions' => 'professions#typeahead_professions'

  get 'welcome/add_profession' => 'welcome#add_profession'
  get 'welcome/add_profile_pic' => 'welcome#add_profile_pic'
  get 'welcome/add_interests' => 'welcome#add_interests'
  get 'welcome/follow_people' => 'welcome#follow_people'

end

app/models/profession.rb
class Profession < ActiveRecord::Base
  validates :name, presence:true, uniqueness: true
  has_and_belongs_to_many :users
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  before_action :set_profession, only: [:show, :edit, :update, :destroy]

  # GET /professions
  # GET /professions.json
  def index
    @professions = Profession.all
  end

  # GET /professions
  # used instead of index because of the bug with typeahed
  def typeahead_professions
    @professions = Profession.all
    render json: @professions
  end

  # GET /professions/1
  # GET /professions/1.json
  def show
  end

  # GET /professions/new
  def new
    @profession = Profession.new
  end

  # GET /professions/1/edit
  def edit
  end

  # POST /professions
  # POST /professions.json
  def create
    @profession = Profession.new(profession_params)

    respond_to do |format|
      if @profession.save
        format.html { redirect_to @profession, notice: 'Profession was successfully created.' }
        format.json { render :show, status: :created, location: @profession }
      else
        format.html { render :new }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professions/1
  # PATCH/PUT /professions/1.json
  def update
    respond_to do |format|
      if @profession.update(profession_params)
        format.html { redirect_to @profession, notice: 'Profession was successfully updated.' }
        format.json { render :show, status: :ok, location: @profession }
      else
        format.html { render :edit }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professions/1
  # DELETE /professions/1.json
  def destroy
    @profession.destroy
    respond_to do |format|
      format.html { redirect_to professions_url, notice: 'Profession was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profession
      @profession = Profession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profession_params
      # params[:profession]
      params.require(:profession).permit(:name)
    end
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/views/professions/_form.html.haml
//= f.simple_fields_for :professions, include_id: false do |p|
//= p.label :name, 'Tell who you are. For example Student, Manager, Bartender...'
//= p.input :name, placeholder: 'Profession', label: false, input_html: { class: 'typeahead' }
= simple_form_for(@profession) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/professions/edit.html.haml
%h1 Editing profession

= render 'form'

= link_to 'Show', @profession
\|
= link_to 'Back', professions_path

app/views/professions/index.html.haml
%h1 Listing professions

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @professions.each do |profession|
      %tr
        %td= link_to 'Show', profession
        %td= link_to 'Edit', edit_profession_path(profession)
        %td= link_to 'Destroy', profession, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profession', new_profession_path

app/views/professions/new.html.haml
%h1 New profession
= simple_form_for @profession do |p|
  = render partial: 'shared/error_messages', locals: { target: @profession }
  = p.input :name, label: false, placeholder: 'Profession'
  = p.button :submit

//= render 'form'

//= link_to 'Back', professions_path

app/views/professions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_profession_path(@profession)
\|
= link_to 'Back', professions_path